# GrowthLife Schema & Blog — Shopify app configuration
name = "GrowthLife Schema & Blog"
handle = "growthlife-schema-blog-1"
client_id = "879d6b174af02d2fbbd82fcc844a3823"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "write_content,read_products,read_themes"

[auth]
redirect_urls = [ "https://shopify.dev/apps/app-home/api/auth" ]
